#!/bin/bash

###
#
# Check VMs on all projects
# Author: HoangDH - daohuyhoang87@gmail.com
# Release: 9-Sep-2017 - 11:14PM
#
###
mkdir -p /etc/check_mk/plugins/
# Delete all configure in mrpe.cfg file
sed -i '/check_vm+/d' /etc/check_mk/mrpe.cfg
# Delete all file check_vm
rm -rf /etc/check_mk/plugins/check_vm+*

source /root/keystonerc_admin

## Get all VMs are running
openstack server list --all-projects > /tmp/instance_list.h2

## Count total VMs 
vms_total=$(cat /tmp/instance_list.h2 | awk  '{ print $3 }' FS="|" | grep -Ev "^ Name|^$"  | wc -l)

## Count VMs running
vms_run=$(cat /tmp/instance_list.h2 | grep -w "ACTIVE" | awk  '{ print $3 }' FS="|" | wc -l)

## Get COM nodes
COMS=$(openstack host list | grep -w "compute" | awk {'print $2'} FS="|" | cut -d " " -f 2 | sort -u)



for COM in $COMS
do	
	instances=$(openstack server list --host $COM --all-projects | awk  '{ print $2 }' FS="|" | egrep -v "^$|^ ID" | cut -d " " -f 2)
	for instance in $instances
	do
		STATUS=$(cat /tmp/instance_list.h2 | grep -w $instance | awk {'print $4'} FS="|" | cut -d " " -f 2)
		NAME=$(cat /tmp/instance_list.h2 | grep -w $instance | awk {'print $3'} FS="|" | cut -d " " -f 2)
		if [ ! "$STATUS" = "ACTIVE" ]
		then
			CODE=2
			IPS=$(cat /tmp/instance_list.h2 | grep -w $instance |  awk {'print $5'} FS="|" | grep -oE "\b([0-9]{1,3}\.){3}[0-9]{1,3}\b")
			echo -e "echo \"$NAME; IP: $(echo $IPS | tr ' ' ';') -- $STATUS\"\nexit $CODE" > /etc/check_mk/plugins/check_vm+$NAME
			chmod +x /etc/check_mk/plugins/check_vm+$NAME
			# Write to mrpe.cfg file
			echo -e "\n$COM-$NAME /etc/check_mk/plugins/check_vm+$NAME" >> /etc/check_mk/mrpe.cfg
		else
			IPS=$(cat /tmp/instance_list.h2 | grep -w $instance |  awk {'print $5'} FS="|" | grep -oE "\b([0-9]{1,3}\.){3}[0-9]{1,3}\b")
			flag_status=""
			CODE=0
			for IP in $IPS
			do
				ping $IP -c 3 > /tmp/instance_ping.h2
				flag=$(cat /tmp/instance_ping.h2 | grep -w 'ttl')
				if [ -z "$flag" ]
				then
					CODE=1
					flag_status=$(echo $flag_status $IP is DOWN)
				else
					flag_status=$(echo $flag_status $IP is UP)
				fi
				rm -rf /tmp/instance_ping.h2
			done
			if [ $CODE = 1 ]
			then
				echo -e "echo \"$NAME; IP: $flag_status -- $STATUS\"\nexit $CODE" > /etc/check_mk/plugins/check_vm+$NAME
				chmod +x /etc/check_mk/plugins/check_vm+$NAME
				# Write to mrpe.cfg file
				echo -e "\n$COM-$NAME /etc/check_mk/plugins/check_vm+$NAME" >> /etc/check_mk/mrpe.cfg
			fi			
		fi
	done
done

sed -i '/^\s*$/d' /etc/check_mk/mrpe.cfg

# Remove temp. files
rm -rf /tmp/instance_list.h2

echo "Server Running: $vms_run; Server non-running: $(expr $vms_total - $vms_run)/$vms_total"
exit 0
